name: Main Workflow

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'react-app/**'
      - '.github/workflows/node*.yml'

jobs:
  call-workflow-nodejs:
    uses: ./.github/workflows/node.js.yml
  call-workflow-s3-sync:
    needs: call-workflow-nodejs
    uses: ./.github/workflows/node-s3-sync.yml
    secrets:
      access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      region: ${{ secrets.AWS_REGION }}
