name: S3-sync workflow

on:
  workflow_call:
    secrets:
      access_key:
        required: true
      secret_key:
        required: true
      region:
        required: true
      bucket_name:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: my-build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.access_key }}
          aws-secret-access-key: ${{ secrets.secret_key }}
          aws-region: ${{ secrets.region }}
      - name: Copy files to the s3 website content bucket
        run:
          aws s3 sync ./ s3://${{ secrets.bucket_name }}/ --delete
