name: Pulumi Workflow
on:
  push:
    branches: [ dev ]
    paths:
      - '.github/actions/**'
      - '.github/**'
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      #- uses: actions/checkout@v2
      - uses: ./.github/actions/echo.yml
